language: python
services:
    -docker
script:
    -make lint
    -make test
    -make docker_build
python:
    - "2.7"
install:
    - make deps
script:
    - make test
after_success:
    -make docker_build
